version: '3'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "80:80"
    expose:
      - 80
  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: nat_server
    ports:
      - '8000:8000'
    expose:
      - '8000'
    depends_on:
      - datastore
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://datastore:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  datastore:
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    expose:
      - '5432'
